-- Jalankan sekali di Supabase Dashboard > SQL Editor.
-- Aplikasi server memakai service-role key; RLS tetap dinyalakan untuk mencegah akses langsung dari browser.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null check (role = 'admin'),
  created_at timestamptz not null default now()
);

create table if not exists public.sections (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('potentials', 'galleries')),
  title text not null,
  description text not null default '',
  image text not null default '',
  alt text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  category text not null,
  name text not null default '',
  owner text not null default '',
  address text not null default '',
  phone text not null default '',
  info text not null default '',
  notes text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.sections enable row level security;
alter table public.items enable row level security;
alter table public.businesses enable row level security;
